#!/bin/sh

### BEGIN INIT INFO
# Provides:	     yusuf
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:	     0 1 6
# Short-Description: TrueSkill
# Description:	     Starts the TrueSkill Daemon
### END INIT INFO

NAME="TrueSkill Daemon"
USER="yusuf"
SCREENREF="trueskill"
BINARYPATH="/home/yusuf/tf2Skill/"
BINARYNAME="python"
PIDFILE="trueskill.pid"

cd "$BINARYPATH"

running(){
   if [ -n "`pgrep -f $BINARYNAME`" ]; then
      return 0
   else
      return 1
   fi
}

start() {
   if ! running; then
      echo -n "Starting the $NAME ...."
      /sbin/start-stop-daemon --start --chuid $USER --user $USER --chdir $BINARYPATH --exec "/usr/bin/screen" -- -dmS $SCREENREF python trueSkill.py
      pgrep -f $BINARYNAME > $PIDFILE
      if [ -s $PIDFILE ]; then
	 echo "Done"
      else
	 echo "Failed"
	 rm $PIDFILE
      fi
   else
      echo "The $NAME is already started"
   fi
}

stop(){
   if running; then
      echo -n "Stopping the $NAME ..."
      kill `cat $PIDFILE`
      while running; do
	 sleep 1
      done
      rm $PIDFILE
      echo "Done"
   else
      echo "The $NAME is already stopped"
   fi
}

case "$1" in
   start)
      start
   ;;
   stop)
      stop
   ;;
   restart)
      stop
      start
   ;;
   status)
      if running; then
	 echo "The $NAME is started"
      else
	 echo "The $NAME is stopped"
      fi
   ;;
   *)
      echo "Usage: $0 (start|stop|restart|status)"
      exit 1
esac
exit 0






